version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GITHUB_REPO_URL=git@github.com:nisar-deriv/infra-tribe-website.git
    env_file:
      - .env
    volumes:
      - .:/app
      - ./data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - ollama
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    expose:
      - "11434"
    volumes:
      - ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh  # Mount the entrypoint script
    restart: always
    entrypoint: ["/entrypoint.sh"]  # Use the custom entrypoint script
volumes:
  ollama: {}