version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=dummy
      - USE_OLLAMA=true
    volumes:
      - .:/app
      - ./data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"