version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=dummy
      - USE_OLLAMA=true
    volumes:
      - .:/app
      - ./data:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    expose:
      - "11434"
    volumes:
      - ollama:/root/.ollama
    restart: always
    environment:
      - ENGINE=llama3 
    command: ["sh", "-c", "ollama pull llama3 && ollama start"]

volumes:
  ollama: {} 